copy D:\workspace\工具库\Common-Bins\Castle.DynamicProxy.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\IBatisNet.Common.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\IBatisNet.Common.Logging.Log4Net.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\IBatisNet.DataAccess.2005.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\IBatisNet.DataMapper.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\IBatisNet.DataMapper\IBatisNet.DataMapper.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\IBatisNet.DataMapper\IBatisNet.DataMapper.pdb "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\log4net.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\web.core.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\web.core.pdb "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\win.core.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\win.core.pdb "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\win.updater.exe "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\win.updater.pdb "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\win.tools.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\System.Data.SQLite.DLL "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\web.core.share.models.dll "..\Solution-Bins" 
copy D:\workspace\工具库\Common-Bins\web.core.share.models.pdb "..\Solution-Bins" 

pause