insert into [smartlife-120301].dbo.Sys_Server  select * from [smartlife-120300].[dbo].Sys_Server;
select * from t_deploy_script;
select * from t_deploy_object;
select * from Sys_DictionaryItem;
select 'insert into '+name+'  select * from [smartlife-120300].[dbo].'+name+';' from sys.tables;


select * from dbo.vsystem_info_columns where column_name='InputCode2';
select * from Oca_FamilyCamera;

insert into Pub_ReminderObject  select * from [smartlife-120300].[dbo].Pub_ReminderObject;
insert into Sys_PlatformApplication  select * from [smartlife-120300].[dbo].Sys_PlatformApplication;
insert into Oca_FamilyCamera  select * from [smartlife-120300].[dbo].Oca_FamilyCamera;
insert into Oca_FamilyMember  select * from [smartlife-120300].[dbo].Oca_FamilyMember;
insert into Oca_MutualAidPerson  select * from [smartlife-120300].[dbo].Oca_MutualAidPerson;
insert into Sys_Tree  select * from [smartlife-120300].[dbo].Sys_Tree;
insert into Sys_Behavior  select * from [smartlife-120300].[dbo].Sys_Behavior;
insert into sysdiagrams  select * from [smartlife-120300].[dbo].sysdiagrams;
insert into Oca_ServiceFamilyResponse  select * from [smartlife-120300].[dbo].Oca_ServiceFamilyResponse;
insert into Sys_MenuBehavior  select * from [smartlife-120300].[dbo].Sys_MenuBehavior;
insert into Sys_Parameter  select * from [smartlife-120300].[dbo].Sys_Parameter;
insert into Pub_GroupMember  select * from [smartlife-120300].[dbo].Pub_GroupMember;
insert into Pub_User  select * from [smartlife-120300].[dbo].Pub_User;
insert into Oca_CC_Ext  select * from [smartlife-120300].[dbo].Oca_CC_Ext;
insert into Sys_Dictionary  select * from [smartlife-120300].[dbo].Sys_Dictionary;
insert into Oca_ServiceVoice  select * from [smartlife-120300].[dbo].Oca_ServiceVoice;
insert into Sys_DictionaryItem  select * from [smartlife-120300].[dbo].Sys_DictionaryItem;
insert into Oca_Ewallet_OldMan  select * from [smartlife-120300].[dbo].Oca_Ewallet_OldMan;
insert into Pub_Group  select * from [smartlife-120300].[dbo].Pub_Group;
insert into Pub_GroupPermit  select * from [smartlife-120300].[dbo].Pub_GroupPermit;
insert into Oca_OldManBaseInfo  select * from [smartlife-120300].[dbo].Oca_OldManBaseInfo;
insert into Oca_Ewallet_Merchant  select * from [smartlife-120300].[dbo].Oca_Ewallet_Merchant;
insert into Pub_UserPermit  select * from [smartlife-120300].[dbo].Pub_UserPermit;
insert into Sys_TreeItem  select * from [smartlife-120300].[dbo].Sys_TreeItem;
insert into Sys_DictionaryItemExtend  select * from [smartlife-120300].[dbo].Sys_DictionaryItemExtend;
insert into Oca_Ewallet_Recharge_Record  select * from [smartlife-120300].[dbo].Oca_Ewallet_Recharge_Record;
insert into Pub_UserRePermit  select * from [smartlife-120300].[dbo].Pub_UserRePermit;
insert into Sys_ApplicationAccessPoint  select * from [smartlife-120300].[dbo].Sys_ApplicationAccessPoint;
insert into Pub_Area  select * from [smartlife-120300].[dbo].Pub_Area;
insert into Oca_Ewallet_Charge_Record  select * from [smartlife-120300].[dbo].Oca_Ewallet_Charge_Record;
insert into sTV_00000  select * from [smartlife-120300].[dbo].sTV_00000;
insert into Pub_Device  select * from [smartlife-120300].[dbo].Pub_Device;
insert into Oca_ServiceReceive  select * from [smartlife-120300].[dbo].Oca_ServiceReceive;
insert into Inc_SyncIn_Resident  select * from [smartlife-120300].[dbo].Inc_SyncIn_Resident;
insert into Oca_ServiceWorkOrder  select * from [smartlife-120300].[dbo].Oca_ServiceWorkOrder;
insert into Cer_Redirect  select * from [smartlife-120300].[dbo].Cer_Redirect;
insert into Pub_DeviceExtendInfo  select * from [smartlife-120300].[dbo].Pub_DeviceExtendInfo;
insert into Cer_ObjectToken  select * from [smartlife-120300].[dbo].Cer_ObjectToken;
insert into Cer_DeployNode  select * from [smartlife-120300].[dbo].Cer_DeployNode;
insert into Pub_MultiLanguageStorageSmall  select * from [smartlife-120300].[dbo].Pub_MultiLanguageStorageSmall;
insert into Pub_MultiLanguageStorageBig  select * from [smartlife-120300].[dbo].Pub_MultiLanguageStorageBig;
insert into Oca_CallCenter  select * from [smartlife-120300].[dbo].Oca_CallCenter;
insert into Pub_Geography  select * from [smartlife-120300].[dbo].Pub_Geography;
insert into Oca_OldManHealthInfo  select * from [smartlife-120300].[dbo].Oca_OldManHealthInfo;
insert into sTV_00$01$01  select * from [smartlife-120300].[dbo].sTV_00$01$01;
insert into Oca_CC_Group  select * from [smartlife-120300].[dbo].Oca_CC_Group;
insert into sTV_00$01$02  select * from [smartlife-120300].[dbo].sTV_00$01$02;
insert into Pub_Attachment  select * from [smartlife-120300].[dbo].Pub_Attachment;
insert into Pub_UserArea  select * from [smartlife-120300].[dbo].Pub_UserArea;
insert into Pub_EntityDefination  select * from [smartlife-120300].[dbo].Pub_EntityDefination;
insert into Oca_CC_SeatExtBind  select * from [smartlife-120300].[dbo].Oca_CC_SeatExtBind;
insert into Oca_OldManDeviceInfo  select * from [smartlife-120300].[dbo].Oca_OldManDeviceInfo;
insert into Pub_EntityDefinationHistory  select * from [smartlife-120300].[dbo].Pub_EntityDefinationHistory;
insert into Oca_CC_SeatExtBindHistory  select * from [smartlife-120300].[dbo].Oca_CC_SeatExtBindHistory;
insert into Oca_OldManLocateInfo  select * from [smartlife-120300].[dbo].Oca_OldManLocateInfo;
insert into Oca_CallRecord  select * from [smartlife-120300].[dbo].Oca_CallRecord;
insert into Sys_Server  select * from [smartlife-120300].[dbo].Sys_Server;
insert into Oca_MerchantServeItem  select * from [smartlife-120300].[dbo].Oca_MerchantServeItem;
insert into Sys_ApplicationAccess  select * from [smartlife-120300].[dbo].Sys_ApplicationAccess;
insert into Oca_MerchantServeMode  select * from [smartlife-120300].[dbo].Oca_MerchantServeMode;
insert into Pub_ServiceStation  select * from [smartlife-120300].[dbo].Pub_ServiceStation;
insert into Pub_Reminder  select * from [smartlife-120300].[dbo].Pub_Reminder;
insert into Oca_OldManFamilyInfo  select * from [smartlife-120300].[dbo].Oca_OldManFamilyInfo;
insert into Oca_OldManConfigInfo  select * from [smartlife-120300].[dbo].Oca_OldManConfigInfo;
insert into Sys_WhiteList  select * from [smartlife-120300].[dbo].Sys_WhiteList;
insert into Sys_ApplicationAccessibility  select * from [smartlife-120300].[dbo].Sys_ApplicationAccessibility;
insert into Oca_ServiceTrackLog  select * from [smartlife-120300].[dbo].Oca_ServiceTrackLog;
insert into Log_SystemJob  select * from [smartlife-120300].[dbo].Log_SystemJob;
insert into Sys_Platform  select * from [smartlife-120300].[dbo].Sys_Platform;
insert into Oca_CallService  select * from [smartlife-120300].[dbo].Oca_CallService;
insert into Sys_Application  select * from [smartlife-120300].[dbo].Sys_Application;
insert into Oca_MerchantServePeriod  select * from [smartlife-120300].[dbo].Oca_MerchantServePeriod;
insert into Sys_Menu  select * from [smartlife-120300].[dbo].Sys_Menu;
insert into Pub_SmsSend  select * from [smartlife-120300].[dbo].Pub_SmsSend;